services:
  - type: web
    name: maestro-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: MONGO_URL
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
